### ISSUE TITLE
Transpile fails for client builds

### ISSUE THREAD

**Issue by DominikTrenz** [feathersjs-ecosystem/feathers-reactive#103]
This module requires:

    "@feathersjs/commons": "^1.4.0",
    "@feathersjs/feathers": "^3.1.1",

Those are untranspiled versions, which will break builds that require to run in non es6 browsers 
(edge, ie11).
Please manually transpile the dependencies or require the `"@feathersjs/client"` version of those modules.

Related:
https://github.com/feathersjs/feathers/issues/608

**Comment by daffl** [comment]
Same issue as #101

**Comment by daffl** [comment]
How to set up Feathers to properly work for client builds outside `created-react-app` is outlined in https://docs.feathersjs.com/api/client.html#module-loaders

**Comment by DominikTrenz** [comment]
Webpack config isn't accessible for Angular CLI users. It is accessible using ng eject, but then the user looses all Angular CLI features, which is not recommended.

Can't we just include transpiled code in the module, which is the recommended way?
http://2ality.com/2017/06/pkg-esnext.html
