### ISSUE TITLE
Socket reconnect. How to?

### ISSUE THREAD

**Issue by DominikTrenz** [feathersjs-ecosystem/feathers-reactive#104]
I'm trying to figure out how to handle socket reconnection. It seems like feathers reactive doesn't handle this reconnections.

Shouldn't that be the case? The only solution i can think of is listening on the socket "reconnected" event and recreate all the observables, but it seems very hacky.

**Comment by daffl** [comment]
Socket reconnection is handled transparently by the underlying library and should not require any intervention at the level `feathers-reactive` is operating. What specifically are the problems you are running into?

**Comment by DominikTrenz** [comment]
1. I subscribe to some services
2. I kill the connection -> reconnect happens
3. The subscriptions are dead and i no longer receive service changes

**Comment by j2L4e** [comment]
Do you still  receive the events in the socket?

**Comment by DominikTrenz** [comment]
No. It seems like the socket is reauthenticated...
Do you have any idea what might be the problem?

Client Code:
```
import * as io from 'socket.io-client';
import * as feathers from '@feathersjs/client';
import * as rx from 'feathers-reactive';

...

this.feathersApp = feathers()
            .configure(feathers.authentication(this.authOptions))
            .configure(feathers.socketio(io(this.wssEndpoint)))
            .configure(rx({
                idField: '_id'
            }));
```
Server Code:
```
const socketio = require('@feathersjs/socketio');
const feathers = require('@feathersjs/feathers');
const express = require('@feathersjs/express');

...

const app = express(feathers());

app.configure(
  socketio(
    (function (io) { socketioHandler(app, io); })
  )
);
app.configure(authentication); // authentication includes all the auth logic
```

**Comment by muhameed-magdy** [comment]
+1

**Comment by bnielsen1965** [comment]
Are there any work arounds for this? When the feathers client reconnects to the feathers server it looks like the server no longer sends the real time events to the new socket connection. But you can still use the client services to call create/remove/etc successfully.

**Comment by daffl** [comment]
Reliable reauthentication has been addressed in Feathers authentication v4. See the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information.
