### ISSUE TITLE
Update to rxjs6 once final

### ISSUE THREAD

**Issue by j2L4e** [feathersjs-ecosystem/feathers-reactive#106]
RxJS 6 is nigh.
We should update the code base and maybe wait for version 6.0.1 or 6.0.2 for a release.

There's a first version of a migration document available over here https://docs.google.com/document/d/12nlLt71VLKb-z3YaSGzUfx6mJbc34nsMXtByPUN35cg/preview#

I think it'll still be a couple of weeks, mainly just opening this so I don't forget about it.

**Comment by j2L4e** [comment]
https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md

**Comment by Clowting** [comment]
Hi! Any idea when the migration will be done?
