### ISSUE TITLE
Reactive mongodb

### ISSUE THREAD

**Issue by jafri** [feathersjs-ecosystem/feathers-reactive#107]
I am using mongodb change streams currently like this in a setup where external daemons constantly update the mongodb database, and I only need to read and query the data (no writes):

```
  const blockStream = Blocks.watch({ fullDocument: 'updateLookup' });

  blockStream.on('change', function(change) {
    app.service('blocks').emit('customEvent', change.fullDocument);
  });
```

Is the best way to simply listen on the frontend like this:
```
app.service('blocks').on("new", data => {
  store.commit('updateBlocks', data)
})
```

Or can feathers-reactive be used here?

**Comment by daffl** [comment]
That should work as long as you set it up as a [custom service event](https://docs.feathersjs.com/api/events.html#custom-events) with the pre-built adapter by passing the [`events` option](https://docs.feathersjs.com/api/databases/common.html#serviceoptions).
