### ISSUE TITLE
All declarations of 'observable' must have identical modifiers.

### ISSUE THREAD

**Issue by dottodot** [feathersjs-ecosystem/feathers-reactive#120]
After updating my angular project to rxjs6.2.1 I started getting the error

```
ERROR in node_modules/feathers-reactive/node_modules/rxjs/internal/symbol/observable.d.ts(4,5): error TS2687: All declarations of 'observable' must have identical modifiers.
```

I believe it just needs the dependency updating in feathers-reactive to resolve this.

**Comment by j2L4e** [comment]
ReactiveX/rxjs#3769

updating package-lock to rxjs 6.2.1 will solve this.

@daffl maybe we should make rxjs a peer dependency (breaking :/) or remove package-lock.json

**Comment by daffl** [comment]
The `package-lock.json` in this repository will not be published and will have no impact on other installations. From [the npm docs](https://docs.npmjs.com/files/package-lock.json):

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

This may be a different issue though.

**Comment by dottodot** [comment]
This repository just needs updating to rxjs 6.2.1 as it a know bug that was fixed in that version.

**Comment by daffl** [comment]
I don't understand why npm does not install the latest of what is in the dependency range but I'll make a patch release with the updated version.
