### ISSUE TITLE
Still no full ES5 support?

### ISSUE THREAD

**Issue by phymous** [feathersjs-ecosystem/feathers-reactive#122]
The `main` attribute of the `feathers-reactive`'s `package.json` points to `lib/index`.
`lib/index` imports `@feathersjs/commons/lib/utils` which itself contains the following ES6 code (snippet):

```
// A set of lodash-y utility functions that use ES6
const _ = exports._ = {
  each (obj, callback) {
    if (obj && typeof obj.forEach === 'function') {
      obj.forEach(callback);
    } else if (_.isObject(obj)) {
      Object.keys(obj).forEach(key => callback(obj[key], key));
    }
  },
...
```

This obviously causes a problem for IE11 due to the lacking ES6 support.
When I import `feathers-reactive/dist/feathers-reactive` instead of just `feathers-reactive`, I get no error in IE 11.

Is this intended?

### System configuration

**Module versions**: `feathers-reactive` 0.7.1

**Browser Version**: IE 11

**Module Loader**: Webpack

**Comment by daffl** [comment]
Yes, this is intended. As you pointed out, the ES5 version can be found by requiring `feathers-reactive/dist/feathers-reactive`.

When using the module directly the same module bundler configuration is necessary as [when using Feathers directly on the client](https://docs.feathersjs.com/api/client.html#module-loaders).

**Comment by daffl** [comment]
It works the same as [using Feathers itself on the client](https://docs.feathersjs.com/api/client.html). You can either [configure your module bundler as documented](https://docs.feathersjs.com/api/client.html#module-loaders) or use the ES5 transpiled version (just like [@feathersjs/client](https://docs.feathersjs.com/api/client.html#feathersjsclient)). Like Feathers, `feathers-reactive` works in Node and on the client and is written with the features that the earliest supported version (6 LTS) of Node supports out of the box - so all standard ES6 (ES2015) features (the current version of JavaScript) without ES modules or anything else that is non-standard or would require other Babel plugins. You can find more for the reasons behind this in https://github.com/feathersjs/feathers/issues/608

A note in the readme for loading the transpiled version would be nice indeed though.
