### ISSUE TITLE
get with query change dosn't work

### ISSUE THREAD

**Issue by dottodot** [feathersjs-ecosystem/feathers-reactive#127]
If I do a get with a query i.e 

```
this.service
      .watch()
      .get(id, {
        query: query
      })
```
then I want to update my view using a new query the request doesn't get sent. It only updates if I change the id. Why is this and how can I fix it?

**Comment by daffl** [comment]
Because the query for `get` requests doesn't matter. A single entry is always identified by id and the resulting stream will send updates every time the entry with that id has been `updated`, `patched`, `created` or `removed`.
