### ISSUE TITLE
Typings support for feathers-reactive

### ISSUE THREAD

**Issue by Ismail-codinglab** [feathersjs-ecosystem/feathers-reactive#164]
I would love to have feathers-reactive typings to be supported, so i can use it in my angular project with typings.

right now it tells me `watch` is not a method of service

**Comment by daffl** [comment]
The typings are in in `feathers-reactive` at https://github.com/feathersjs-ecosystem/feathers-reactive/blob/master/index.d.ts. Make sure you `import 'feathers-reactive'` somewhere.

**Comment by Ismail-codinglab** [comment]
I did not got it working
![image](https://user-images.githubusercontent.com/48755937/61291339-8cde6f00-a7ce-11e9-89cd-c5ab937eb47c.png)
![image](https://user-images.githubusercontent.com/48755937/61291324-83ed9d80-a7ce-11e9-84e3-f9a2284ca135.png)

**Comment by Ismail-codinglab** [comment]
I guess a version mismatch because @types/feathersjs__feathers@3.1.4 won't work with feathers-reactive@0.8.1 but 3.1.5 will
