### ISSUE TITLE
How to unsubscribe() ?

### ISSUE THREAD

**Issue by KrishnaPG** [feathersjs-ecosystem/feathers-reactive#175]
Could not find in the examples how to unsubscribe.

Subscribing to find() as below on the client side when a component is mounted:
````
this.fClient.service('devices').watch().find().subscribe(console.log);
````
The problem is, there is apparently no way to unsubscribe when the component is being unmounted. This creates multiple duplicate subscriptions when the component is mounted multiple times.

**Comment by daffl** [comment]
The return value is an [RXJS observable](https://rxjs.dev/guide/observable) so you should just be able to `.unsubscribe`:

```js
const subscription = this.fClient.service('devices').watch().find().subscribe(console.log);
// Later:
subscription.unsubscribe();
```

**Comment by KrishnaPG** [comment]
Thank you @daffl It worked.
