### ISSUE TITLE
Failure to import in v0.10

### ISSUE THREAD

**Issue by fusillijerry89** [feathersjs-ecosystem/feathers-reactive#203]
v0.10 cannot be imported using import statement.

Please fix

**Comment by RobMaple** [comment]
I've just run into this error. In my case it's specifcally when building for production using vite (therefore rollup). In dev mode its fine. The error seems to be related to the import of the "getParamsPosition" in feathers-reactive/src/resource.js.

I'm not 100% sure but I'm guessing its to do with the mixing of ES imports / cjs exports.

**Comment by bitflower** [comment]
@RobMaple See my comment here:
https://github.com/feathersjs-ecosystem/feathers-reactive/issues/193#issuecomment-1546395700

**Comment by daffl** [comment]
Should be fixed now in v0.11.0 via https://github.com/feathersjs-ecosystem/feathers-reactive/pull/211
