### ISSUE TITLE
smart strategy + matcher don't filter initial find

### ISSUE THREAD

**Issue by eddyystop** [feathersjs-ecosystem/feathers-reactive#35]
``` javascript
app.configure(rx(RxJS, { listStrategy: 'smart' }));
app.service('meetings').rx({
  idField: '_id',
  matcher: query => item => item.onOff === 'on'
});
meetings.find().subscribe(meetings => { console.log(meetings); })
```

This prints all items when `subscribe` is called the first time, rather than filtering them. I don't know if this is intentional, but `meetings.find({ query: { onOff: 'on' }})` would filter them first.

That initial list gets filtered properly on the first patch event (and I assume the update event also),
but it will not be filtered if the first event is:
- create an item that satisfies the matcher.
- remove an item that satisfied the matcher (I assume same if matcher not satisfied).

**Comment by daffl** [comment]
This should be fixed now.
