### ISSUE TITLE
How does the sorter work?

### ISSUE THREAD

**Issue by dottodot** [feathersjs-ecosystem/feathers-reactive#49]
It's not really clear from the documentation how the sorter option should be used. I'm currently having issues with the sort order after making a change to a list of items (i.e the sort order isn't the same as the original request) and wondering if I need to be using this option to rectify the problem.

**Comment by daffl** [comment]
What exactly are you trying to do? Creating your own sorter might be a bit complicated (the default one is being created from the query parameters using internals of the `feathers-memory` database adapter).

If you are just changing the query you might want to look at the solution from https://github.com/feathersjs/feathers-reactive/issues/39

**Comment by dottodot** [comment]
I'm actually using that example just getting some strange behaviour.

This is the query I have set up
```
    this.query = new BehaviorSubject({
      $limit: 50,
      $skip: 0,
      published: true,
      $sort: {
        materialType: 1,
        weight: 1
      }
    });
```
then later on I have 
```
  getItems() {
    this.serviceSub = this.query.mergeMap(query => {
       return this.mainService.find({ query: query })
    });
    this.serviceSub.subscribe(resp => {
      this.total = resp.total;
      this.items = resp.data;
      this.isLoading = false;
    }); 
  }
```
this loads the data as expected, but if i then do a patch update on an item such as
```
this.mainService.patch(id, {
      published: status
    });
```
the list is no longer sorted correctly, it seems to be sorted just by the weight attribute.

Oddly though, if I remove $limit and $skip from the query the sorting seems to stay correct.

**Comment by daffl** [comment]
`$skip` is definitely one of the edge cases where the normal `smart` strategy might not work because we won't know if the changed entry even still goes into that list.

If just the sorting is off there might still be a bug though. What database are you using?

**Comment by dottodot** [comment]
I'm actually using the `always` strategy as I was finding the list would become empty when doing the same patch. I'm using mongo/mongoose for the database.

**Comment by daffl** [comment]
If the list becomes empty you may not have set the [correct idField property](https://github.com/feathersjs/feathers-reactive#options).

**Comment by dottodot** [comment]
Already have that set like

```
configure(rx(RxJS, {listStrategy: 'always', idField: '_id'}))
```
