### ISSUE TITLE
Subscriptions with $contains and $search are not reactive

### ISSUE THREAD

**Issue by jpsear** [feathersjs-ecosystem/feathers-reactive#53]
### Steps to reproduce

Subscribe to a service, using a `$search` query:

`app.service('/service').find({ query: { firstName: { $search: '^james' } } }).subscribe(callback)`

### Expected behavior
The client receives updates when a document is added/removed/changed that matches the query

### Actual behavior
The client does not receive the update

Upon calling the initial registration of the subscription, all data is returned as expected. But, the subscription isn't reactive — so we don't receive any more data.

**Comment by daffl** [comment]
Only the [official query syntax](https://docs.feathersjs.com/api/databases/querying.html) is supported. `$contains` and `$search` are currently still database specific extensions.

**Comment by daffl** [comment]
To get updates for queries with those parameters the `always` [list strategy](https://github.com/feathersjs/feathers-reactive#list-strategies) can be used for now.

**Comment by DominikTrenz** [comment]
The official query syntax does not work for me. Especially $gt and $gte

`this.someService.find({
  query: {
    $sort: {
      start: 1
    },
    start: {
      $gte: moment().startOf('day').toDate()
    }
  },
  rx: {
    listStrategy: 'always'
  }
});`

**Comment by daffl** [comment]
@DominikTrenz This is unfortunately not enough information to reproduce and should also probably be a separate issue.

**Comment by DominikTrenz** [comment]
#62 I created a new issue. Please let me know if you need more information

**Comment by daffl** [comment]
#97 adds the ability to add [custom sift expressions](https://github.com/crcn/sift.js/#custom-expressions) which allows to implement non-standard special keywords:

```js
const feathersRx = require('feathers-reactive');

feathersRx.sift.use({
  $search(a, b) {
    return (a & b) ? 0 : -1; // 0 = exists, -1 = doesn't exist
  }
});
```

**Comment by jskrzypek** [comment]
Awesome! An elegant solution! Thanks, @daffl
