### ISSUE TITLE
subscribing to query with $populate does not see any updates even with listStrategy=always

### ISSUE THREAD

**Issue by gbevan** [feathersjs-ecosystem/feathers-reactive#60]
### Steps to reproduce
e.g.
```
.find({query: {
   $populate: [
      {path: 'pets'}
   ]
}})
.subscribe(...
```
Service with listStrategy=always

If I comment out the 

### Expected behavior
whenever a new document is added (via api), the subscribed query should fire with the updated results.

### Actual behavior
Nothing happens.  the subscribe does not fire with the updated query.

Deleting a document works fine.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
```
feathers-2.1.2
feathers-reactive-0.4.1
feathers-mongoose-5.1.0
feathers-socketio-2.0.0
```
**NodeJS version**:
v6.10.2

**Operating System**:
ubuntu 16.04.2 LTS

**Browser Version**:
Chrome-58.0.3029.96 (64-bit)

**React Native Version**:
rxjs-5.4.0
**Module Loader**:
Webpack-2.5.1

**Comment by daffl** [comment]
Probably very similar to #56 and #53. Non-[standard](https://docs.feathersjs.com/api/databases/querying.html) parameters are treated as normal fields, there should be a way to specify fields to exclude when checking a query for reactivity (although I'm surprised it still doesn't work with the `always` strategy).

**Comment by ralph-fuechtenkort** [comment]
Good Morning, i read that but do not understand what this finally means?
Dies $populate simply not work reactive?

**Comment by daffl** [comment]
No. It means that `$populate` is interpreted as a query parameter and not as a special parameter. I should have a fix for this shortly.

**Comment by ngamulin** [comment]
@daffl , has there been any update related to $populate issue?

I have been trying to populate a query without success.
These are the schemas:

`module.exports = function (app) {
  const mongooseClient = app.get('mongooseClient');
  const { Schema } = mongooseClient;
  const channels = new Schema({
    name: String,
    type: String,
    description: String,
    hashtags: [String],
    fbCodeUrl: String,
    parent: {
      type: Schema.Types.ObjectId,
      ref: 'channels'
    },
    children: [{
      type: Schema.Types.ObjectId,
      ref: 'channels'
    }],
    creator: {
      type: Schema.Types.ObjectId,
      ref: 'users'
    },
    admins: [{
      type: Schema.Types.ObjectId,
      ref: 'users'
    }],
    threads: [{
      thread: {
        type: Schema.Types.ObjectId,
        ref: 'threads'
      },
      timeLastActive: { type: Date, default: Date.now }
    }],
    initializationPermissions: {
      customer: Boolean,
      channelAdmin: Boolean
    },
    actionButtons: {
      type: Schema.Types.ObjectId,
      ref: 'fbButtonsSet'
    },
    greeting: String,
    includeActionButtons: {
      type: Boolean,
      default: false
    },
    customers: [{
      type: Number,
      ref: 'customers'
    }]
  });

  return mongooseClient.model('channels', channels);
};`

`module.exports = function (app) {
  const mongooseClient = app.get('mongooseClient');
  const { Schema } = mongooseClient;
  const users = new Schema({

    email: {type: String, unique: true},
    password: { type: String },
    name: String,

    subordinates: [{
      type: Schema.Types.ObjectId,
      ref: 'users'
    }],


    googleId: { type: String },

    facebookId: { type: String },

    facebook: {
      token: String,
      name: String,
      email: String
    },

    timeJoined: { type: Date, default: Date.now },

    isVerified: { type: Boolean },
    verifyToken: { type: String },
    verifyExpires: { type: Date },
    verifyChanges: { type: Object },
    resetToken: { type: String },
    resetExpires: { type: Date }

  }, {
    timestamps: true
  });

  return mongooseClient.model('users', users);
};`

and this is the query which is supposed to populate channel with user:

`app.service('channels').find({query: { "$populate": 'creator', _id: [channel_id]}}).then(channelsInfo => {...});`

**Comment by baljeet** [comment]
Is there any fix to this?

**Comment by daffl** [comment]
You have to got through the query (https://github.com/feathersjs-ecosystem/feathers-reactive/blob/master/src/strategies.js#L11 and https://github.com/feathersjs-ecosystem/feathers-reactive/blob/master/src/strategies.js#L35) and remove properties that start with `$`.

**Comment by jskrzypek** [comment]
@baljeet @ngamulin You can see my issue #82 for an example of how we solved this without a lot of extra code.
