### ISSUE TITLE
Update rxjs to 5.5

### ISSUE THREAD

**Issue by j2L4e** [feathersjs-ecosystem/feathers-reactive#76]
RxJS 5.5 with [lettable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md) is out.
The way we import operators now patches `Observable.prototype` creating blind dependencies. Moving to lettables would avoid that.
5.5 still allows the prototype operators, so this would not impose a breaking change per se.
However applications that rely on an operator that feathers-reactive imported without importing it on their own, will break. This is easy to debug and fix though.

**Comment by daffl** [comment]
Closed via #95
