### ISSUE TITLE
patch subscribe fires twice

### ISSUE THREAD

**Issue by dottodot** [feathersjs-ecosystem/feathers-reactive#80]
Im changing my angular app from using the http client to feathers reactive and sockets but seeing behaviour that I can't understand.

In my service I have the following
```
  update(id: number | string, data: any) {
    return this.feathers
      .service(this.endpoint)
      .watch()
      .patch(id, data);
  }
```
and in my component I have
```
  updateItem(data: any) {
    this.service.update(this.id, data).subscribe(resp => {
      console.log('navigate');
    });
  }
```
But doing that causes navigate to fire twice.  The equivalent using angular http only fires once. i.e
```
  update(id: number | string, data: any) {
    return this.http
      .patch(`${this.host}/${this.endpoint}/${id}`, data)
      .map(res => res.json());
  }
```

**Comment by j2L4e** [comment]
You are watching it. It will fire as often as data is updated. If you want to just get the response, use the Promise based service, i.e. `feathers.service('...').patch(...)` or use the `.first() / .take(1)` operator. Imho there's little benefit in watching a `.patch`.

**Comment by dottodot** [comment]
I see, thankyou.
