### ISSUE TITLE
[Docs proposal] Add more documentation about the matcher option

### ISSUE THREAD

**Issue by jskrzypek** [feathersjs-ecosystem/feathers-reactive#82]
Currently there are three issues open #53 #56 #60  (and I believe a few that are closed as well) that all stem from the same behavior of the (`matcher()` from `feathers-commons@0.8.7`)[https://github.com/feathersjs/commons/blob/auk/src/utils.js#L146-L171] which is the default matcher function used by feathers-reactive.

The specifics of the behavior are such that many complex queries will cause the matcher to return false all the time, dropping the events rather than simply ignoring the parts of the query it doesn't understand.

I don't know if this is likely to be changed for some later release or update with Buzzard, but I think before any code change is made, providing more documentation or a warning about the `matcher` option might help avoid a lot of confusion, as this is a single point of configuration that can solve all of the related issues. E.g. in our code we solved this simply doing something like the following:

```js
const { matcher, omit } = require('feathers-commons/lib/utils');

feathers()
    .configure(hooks())
    .configure(socketio(this.socket, { timeout: 10000 }))
    .configure(rx({
        idField: '_id',
        strategy: 'always',
        // fix for $nonstandardSyntax bug
        matcher: (query) => matcher(omit(query, ['$nonstandardSyntax']))
    }));
```

It took us almost a week to get around to figuring out that this was the only fix we needed, so I imagine there are others who will hit the same pitfall...

**Comment by daffl** [comment]
In the latest version via #97 all `$` prefixed query parameters are now being ignored.
