### ISSUE TITLE
Cannot find module 'feathers' when using @feathersjs/client

### ISSUE THREAD

**Issue by nueko** [feathersjs-ecosystem/feathers-reactive#83]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by lusid** [comment]
Basically, it seems this library is not compatible with Feathers 3.0 (at least not with the naming convention change). Any plans on fixing this?

**Comment by daffl** [comment]
This module does not depend on `feathers`. I just tried the Readme example with v3 and am not seeing any issues.

**Comment by lusid** [comment]
Sorry, you are completely right. Must remember to not look through open issues as kneejerk reaction to a typo. :-)

**Comment by lusid** [comment]
Actually, no, there does seem to be some issue. My Angular app is reporting:

`ERROR in node_modules/feathers-reactive/index.d.ts(2,48): error TS2307: Cannot find module 'feathers'.`

**Comment by j2L4e** [comment]
delete the typings and you're golden. For now. We'd need to remove those because the feathers ones have moved to DefinitelyTyped.

**Comment by lusid** [comment]
Yep, everything seems good now. Thanks!

**Comment by oussamaABID** [comment]
my fix, work for my
```
import { Injectable } from '@angular/core';
import * as io from 'socket.io-client';
import * as feathers from '@feathersjs/feathers';
import * as socketio from '@feathersjs/socketio-client';
import * as feathersRx from 'feathers-reactive/dist/feathers-reactive.js';
```

**Comment by netzwerch** [comment]
Thanks @oussamaABID, for me it worked too. But for some reason it broke my angular-cli application so that it could not load RxJS extensions during runtime.
So now I helped myself by always deleting the index.d.ts in the npm scripts.
`"fix-problem": "rm ./node_modules/feathers-reactive/index.d.ts 2>/dev/null || :",`

**Comment by j2L4e** [comment]
you can add a stub to your project for now: https://github.com/feathersjs-ecosystem/feathers-chat-angular/blob/master/src/typings.d.ts#L7-L14

**Comment by oussamaABID** [comment]
@netzwerch with this versions ?
```
 "dependencies": {
    "@angular/animations": "5.2.0",
    "@angular/cdk": "^5.1.0",
    "@angular/common": "5.2.0",
    "@angular/compiler": "5.2.0",
    "@angular/core": "5.2.0",
    "@angular/forms": "5.2.0",
    "@angular/http": "5.2.0",
    "@angular/material": "5.1.0",
    "@angular/platform-browser": "5.2.0",
    "@angular/platform-browser-dynamic": "5.2.0",
    "@angular/router": "5.2.0",
    "@feathersjs/client": "3.3.0",
    "core-js": "2.4.1",
    "feathers-authentication-management": "2.0.0",
    "feathers-reactive": "0.5.4",
    "rxjs": "5.5.6",
    "socket.io-client": "2.0.4",
    "zone.js": "0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.7",
    "@angular/compiler-cli": "5.2.0",
    "@angular/language-service": "5.2.0",
    "@types/jasmine": "2.8.3",
    "@types/jasminewd2": "2.0.2",
    "@types/node": "6.0.60",
    "codelyzer": "4.0.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "1.2.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.2",
    "ts-node": "4.1.0",
    "tslint": "5.9.1",
    "typescript": "2.5.3"
  }
```
