### ISSUE TITLE
Subscription doesn't report updates when used with buzzard

### ISSUE THREAD

**Issue by compwright** [feathersjs-ecosystem/feathers-reactive#99]
### Steps to reproduce

Upgrade the sample todo app to uses FeathersJS v3 on the front end and back end.

### Expected behavior
It should work normally. Any updates should reflect on the page in real time.

### Actual behavior
No updates reflect on the page until the next page reload.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions**

- create-react-app 1.5.2
- feathers-cli 3.6.1
- @feathersjs/feathers 3.1.3
- @feathersjs/client 3.4.2
- feathers-reactive 0.6.0

**NodeJS version**: 8

**Operating System**: Mac OS X

**Browser Version**: Google Chrome 64.0.3282.167

**React Native Version**: n/a

**Module Loader**: Webpack (via create-react-app)

**Comment by compwright** [comment]
See source code here - https://github.com/compwright/react-todos-feathers3

**Comment by daffl** [comment]
Mentioned in the [channels section in the migration guide](https://docs.feathersjs.com/migrating.html#adding-channels):

> Very important: The channels.js file shown above will publish all real-time events to all authenticated users. This is already safer than the previous default but you should carefully review the [channels](https://docs.feathersjs.com/api/channels.html) documentation and implement appropriate channels so that only the right users are going to receive real-time events.

**Comment by compwright** [comment]
The repo I linked to was generated with the latests feathers-cli, and includes [this channels.js file](https://github.com/compwright/react-todos-feathers3/blob/master/server/src/channels.js). Is it incorrect?

**Comment by daffl** [comment]
Yes, both `channels.js` files only send events to authenticated users. Your demo application client is not authenticating its connection.

You can verify that it works by temporarily changing https://github.com/compwright/react-todos-feathers3/blob/master/server/src/channels.js#L47 to `return app.channel('authenticated', 'anonymous');`

**Comment by compwright** [comment]
That worked! thanks :)
